ALTER TABLE public.doctors
  ADD COLUMN IF NOT EXISTS specialization VARCHAR(200),
  ADD COLUMN IF NOT EXISTS bio TEXT,
  ADD COLUMN IF NOT EXISTS photo_url TEXT,
  ADD COLUMN IF NOT EXISTS working_hours JSONB,
  ADD COLUMN IF NOT EXISTS consultation_duration_mins INTEGER DEFAULT 30,
  ADD COLUMN IF NOT EXISTS is_active BOOLEAN DEFAULT true,
  ADD COLUMN IF NOT EXISTS accepting_patients BOOLEAN DEFAULT true;
